version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - utfpr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: tracking-api
    image: docker.io/jeffreyutfpr/tracking-api:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DLL_AUTO: update
      JDBC_DRIVER: org.postgresql.Driver
      SERVICE_PROVIDER: utfpr.edu.*
    depends_on:
      - db
    networks:
      - utfpr
    ports:
      - "8282:8282"

  web:
    container_name: tracking-web
    image: docker.io/jeffreyutfpr/tracking-web:latest
    depends_on:
      - api
    networks:
      - utfpr
    ports:
      - "3000:3000"

networks:
  utfpr:
    name: utfpr
    driver: bridge

volumes:
  postgres-data: